### ISSUE TITLE
Error appears in the Progress log when installing Calendar Application (Pro)

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-mocca-calendar#21]
Steps to reproduce

1. Click on Administer Wiki
2. Click on Extensions > Extensions
3. Search for Calendar Pro
4. Click on Install and Continue

Expected results: The application is installed successfully.

Actual results: An error message appears in the Progress log "Unexpected error when trying to find extension dependency [Full Calendar Macro 2.0.4] in repository [public-store-snapshots:maven:https://nexus.xwiki.com/nexus/content/repositories/public-store-snapshots/]: "

Environment: Windows 10, IE 11, XWiki 10.10 with MySQL 5.7

![calendarpro](https://user-images.githubusercontent.com/40691112/50001711-5f1a1900-ffa6-11e8-8930-216639584651.jpg)

**Comment by mflorea** [comment]
We just made the ``public-store-snapshots`` repo public (is was protected) so the warning message should not appear anymore. It's still interesting to find why the ``public-store-snapshots`` repo is used in this case since you're installing a final version so it should look into ``public-store-releases`` instead.

**Comment by acotiuga** [comment]
The issues is not reproducing anymore on XWiki 11.7. The progress log is clean.
