### ISSUE TITLE
firstDay set to 0 should display Monday as first day in the calendar instead of Sunday for ES language set in Wiki

### ISSUE THREAD

**Issue by oanalavinia** [xwikisas/application-mocca-calendar#41]
**Steps to reproduce:**

1. Set wiki language to Spanish
2. Go to Calendar -> Other Events
3. Observe that the first day of the week is Monday (Lunes)
4. Edit the Mocca Calendar Macro of the page to have firstDay = 0

**Expected Result:**
Since first day of the week is Monday, 0 should mean that Monday (Lunes) is left as the first day.

**Actual Result:**
Sunday (Domingo) is displayed as the first day of the week.
This is contrary to the behavior that is for a EN wiki, where the first day of the week is Sunday and setting firstDay = 0 will let Sunday as the first day.

The same behavior is reproduced for FR language

Before setting firstDay = 0
![before_setFirstDay](https://user-images.githubusercontent.com/22794181/86266239-9292b780-bbcd-11ea-87c8-3f7ee9d68850.png)

After setting firstDay = 0
![after_set_firstDay](https://user-images.githubusercontent.com/22794181/86266243-958da800-bbcd-11ea-8352-d9365695e0c7.png)

**Comment by oanalavinia** [comment]
Investigation: this issue is related to how in [here (fullcalendar)](https://github.com/xwiki-contrib/macro-fullcalendar/blob/master/macro-fullcalendar-ui/src/main/resources/Calendar/Translations.es.xml#L44) the names of the week days start from Sunday, which will remain on position 0

**Comment by lucaa** [comment]
@oanalavinia see #54 for the same property , I don't consider this issue as a bug as long as the parameter can be used properly. In the end, 0 is just a number, as long as we agree that it means "Sunday" the is no issue for it to mean "Sunday" for all locales.

Just that it's clear for me, in sentences like these "Since first day of the week is Monday, 0 should mean that Monday (Lunes) " and "a EN wiki, where the first day of the week is Sunday" , when you're talking about the "first day" being monday in spanish and sunday in english, I guess you mean the default values for those locales, no? (we don't have a "first day of the week" setting in the wiki administration, no?). In that case, note that the first day of the week is not specific to a language but to a complete locale, including country.

**Comment by oanalavinia** [comment]
Yes, when I said the "first day" being monday in spanish and sunday in english, I was talking about the default value of the locale.
Indeed, this issue should be closed since this is the behavior stated in the documentation. 

I have added also a comment on [#54](https://github.com/xwikisas/application-mocca-calendar/issues/54#issuecomment-734139186) related to this issue.

**Comment by oanalavinia** [comment]
Closing this since since, as mentioned, the first day of the week is specific to the locale.
