### ISSUE TITLE
Agenda tab appears as "plainList" and doesn't show any results

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-mocca-calendar#42]
Steps to reproduce:

1. Create some events in the past, present and in the future on the same or different calendars
2. Click on the "Agenda" tag
3. Click on the previous and next buttons

Expected results: The past / present and future events are shown in the respective selection. The previous and next buttons are disabled when the user reaches the end of the events.

![OldView](https://user-images.githubusercontent.com/40691112/87932114-a4140480-ca93-11ea-9f76-859b2e44a0b3.jpg)

Actual results: No events are shown, the tag Agenda appears as "plainList".

![NoAgenda](https://user-images.githubusercontent.com/40691112/87932108-a2e2d780-ca93-11ea-8d2f-4fb8a02a16ed.jpg)

Environment: Windows 10, XWiki 12.5.1 with MySQL 8.0 and IE 11, Calendar Application (Pro) 2.8.10

**Comment by acotiuga** [comment]
The upgrade to [Full Calendar Macro 2.0.4](https://extensions.xwiki.org/xwiki/bin/view/Extension/FullCalendar%20Application#Hv2.0.4) determined some changes in the UI, implemented in (https://github.com/xwikisas/application-mocca-calendar/commit/3e306661b34f907ded73b187ce6a00594ca45d09). One of them is the usage of the `plainList` naming over the `agenda`. The bug about not listing the events in `plainList` view is caused by the usage of the undefined `moment` library.

**Comment by acotiuga** [comment]
New look in the `Plain list` view:
![listeSimple](https://user-images.githubusercontent.com/8121819/100093599-6fa8be80-2e60-11eb-9d2b-b5650ddea24c.png)

**Comment by acotiuga** [comment]
For the "The previous and next buttons are disabled when the user reaches the end of the events." I created a new ticket: #56
