### ISSUE TITLE
Wrong documentation of the "first day of the week" parameter of the calendar macro

### ISSUE THREAD

**Issue by lucaa** [xwikisas/application-mocca-calendar#54]
The hint of the First day of the week parameter of the calendar macro instructs to use 6 for Monday, when the correct value is actually 1, 6 is for Saturday:

![image](https://user-images.githubusercontent.com/657716/100266613-65ff8380-2f52-11eb-8a8d-f4dca1e25bb0.png)

The other available languages of the application should be checked as well.

**Comment by oanalavinia** [comment]
Related to #41 , the documentation should also be updated since it says `Leave empty for Sunday`, but in case the wiki language is set, for example, to Spanish, leaving `firstDay` empty will display Monday as the first day, not Sunday.

An idea could be to say that an empty value means the default day of the locale.
Or maybe the translations should be updated to specify the default first day of the locale (for example, in case of Spanish to have `leave empty for Monday`), but this last idea could mean to still have the problem in case the wiki language has no translations for it.

**Comment by lucaa** [comment]
> Or maybe the translations should be updated to specify the default first day of the locale (for example, in case of Spanish to have leave empty for Monday)

As I said on the other issue, you can have the same language for multiple locales, so I am not sure we'd necessarily be getting it right if we'd put the info in the translation. So I would say the documentation should say the default of the current locale would be used and that's it.
