### ISSUE TITLE
Extra day is included in an all day event when created by selecting a section of the calendar

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-mocca-calendar#69]
Seems that https://github.com/xwikisas/application-mocca-calendar/issues/55 is still reproducing.

Steps to reproduce:

1. Select a period eg. 3 days in Calendar view
![3daysSelected](https://user-images.githubusercontent.com/40691112/141823025-006859b5-bb6b-4aff-8520-273da6832034.jpg)

Expected results: The Start and End date correspond with the selection the user made. 

Actual results: One more day is added to the End date.
![PopUpResult](https://user-images.githubusercontent.com/40691112/141823062-bdbdad36-d267-4280-b55b-d26b2ceeeb80.jpg)

Environment: Windows 10, XWiki 12.5.1 with MySQL 8.0 and IE 11, Firefox 94, Edge and Chrome 95, Calendar Application (Pro) 2.10.1

**Comment by ClemensRobbenhaar** [comment]
The fix for issue #55 took only the display of events into account after they are created.
Fixed for event creation, too, in 682769009

**Comment by lucaa** [comment]
This was a complex issue when it was fixed for #55 , because of the way calendar events are handled by fullcalendar: the endtime of a calendar on fullcalendar is considered to be exclusive, or something like that. I don't remember the exact details, but I remember it was not easy to actually find a way to conciliate the all day events and the events that have a time specified.

For an event with a specified time, when it has start date 15h00 and end date 16h00, you actually assume it takes 60 minutes, starting with minute 0 from hour 15 and ending with minute 59 of hour 15 (so, until 15:59 inclusive and excluding 16h00).
However, for an all day event, we apparently don't accept that the end date is 21/10/2021 00:00, _exclusively_ (by the same rule as above). So an exact 72 hours event won't stop at 18/10/2021 00:00 and end at 21/10/2021 00:00 (exclusively) but somehow stop somewhere in the day of the 20th (how?).

So I think because of these difficulties there was some decision made that made sense to end the all day events the day after. I'm not saying it's necessarily a good idea, I'm saying we need to define a rule that works, and potentially for which a 24h event is equivalent, in terms of start date and end date with an 'all day' event. On this topic always assume that the risk that a new bug is introduced when some bug is fixed is high.
